deployMain:
  stage: deploy
  script:
    - curl "https://api.telegram.org/bot$TG_LUPINE_GUY/sendMessage?chat_id=-1001444185267&text=درحال دیپلوی هلپر%0A$(git log -1 --pretty=%B)"
    - sudo apt-get install -y python3-pip
    - sudo pip3 install docker-compose
    - sudo docker image prune -f
    - echo "HELPERS=$Helpers_Dict" > .env
    - echo "TG_LUPINE_GUY=$TG_LUPINE_GUY" >> .env
    - echo "ROLE_SAVER_TOKEN=$ROLE_SAVER_TOKEN" >> .env
    - sudo docker-compose -f docker-compose.yml build --no-cache
    - sudo docker-compose -f docker-compose.yml up -d
    - curl "https://api.telegram.org/bot$TG_LUPINE_GUY/sendMessage?chat_id=-1001444185267&text=اتمام دیپلوی هلپر"

  only:
    - master
  tags:
    - mainserver
